# Generated by Django 4.1.5 on 2023-03-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(default=None, max_length=150)),
                ('contents', models.FileField(default=None, upload_to='uploaded_newsletters/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('nickname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('breed', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('toy', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            options={
                'ordering': ['fullname', 'nickname', 'gender', 'breed', 'age', 'toy', 'image'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('conf_num', models.CharField(blank=True, max_length=15, null=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
