# Generated by Django 4.1.5 on 2023-03-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0003_alter_newsletter_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='contents',
            field=models.FileField(default=None, upload_to='uploaded/'),
        ),
    ]
